// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdrqOUCohNShqYScYaYjJQ8Yap1bDsI7g',
    appId: '1:72057930975:web:af7da31c0084263c5d956a',
    messagingSenderId: '72057930975',
    projectId: 'store-b7396',
    authDomain: 'store-b7396.firebaseapp.com',
    storageBucket: 'store-b7396.firebasestorage.app',
    measurementId: 'G-0Q6EF10MV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPAwisp4TnxCSMhdg_9bAm1U9sMSyLNIA',
    appId: '1:72057930975:android:26063a5c5978a3485d956a',
    messagingSenderId: '72057930975',
    projectId: 'store-b7396',
    storageBucket: 'store-b7396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOyDpU-lbl8_mPr4jIhcFjMYRfq9C9iNw',
    appId: '1:72057930975:ios:8e20f0144a8494455d956a',
    messagingSenderId: '72057930975',
    projectId: 'store-b7396',
    storageBucket: 'store-b7396.firebasestorage.app',
    iosBundleId: 'com.example.shopStore',
  );

}